#!/bin/sh

#if program not(!) running, run it
# usage: 
# wise-launch firefox

# idea behind: 
# I use it on tiling wm to run a program if it's not
# and just switch to tag with program if it's open (don't open new instance of it)

if ! pgrep -x "brave" > /dev/null
then
   brave --enable-features=VaapiVideoDecoder
fi
